version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-getJIRAData"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ez4ak2aargkb"
s3_prefix = "sam-getJIRAData"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
