AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  getDevOpsKPIs

  Sample SAM Template for getDevOpsKPIs
  
Globals:
  Function:
    Timeout: 10
    Environment: 
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  GetJIRADataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: getJIRAData/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Tracing: Active
      Role: !GetAtt GetJIRADataRole.Arn
      Events:
        GetJIRAData:
          Type: Schedule
          Properties:
            Description: "Schedule to get fresh JIRA data each hour"
            Enabled: True
            Name: "sam-getJIRADataSchedule"
            Schedule: "cron(0 * ? * MON-FRI *)"
  GetJIRADataRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "Role to provide access for Lambda function to get JIRA data"
      RoleName: sam-GetJIRADataRole
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [ {
            "Effect": "Allow",
            "Principal": {
              "Service": "lambda.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          } ]
      }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies: 
        - PolicyName: GetJIRADataS3Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:GetObjectVersion
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:GetLifecycleConfiguration
                - s3:PutLifecycleConfiguration
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::sam-jiradata-dh
                - arn:aws:s3:::sam-jiradata-dh/*
              Effect: Allow
        - PolicyName: GetJIRADataSSMPathAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement: 
              - Action:
                  ssm:DescribeParameters
                Resource: "*"
                Effect: Allow
              - Action: 
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:GetParametersByPath
                Resource: arn:aws:ssm:ap-southeast-2:346327484579:parameter/getJIRAData/*
                Effect: Allow


        
  JIRADataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "sam-jiradata-dh"
  JIRAUserName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/getJIRAData/username"
      Description: "basic-auth username for JIRA instance"
      Type: String
      Value: "Please set a value"
  JIRAToken:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/getJIRAData/token"
      Description: "basic-auth token for JIRA instance"
      Type: String
      Value: "Please set a value"
  JIRASite:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/getJIRAData/site"
      Description: "site name for JIRA instance"
      Type: String
      Value: "Please set a value"
  JIRAJql:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/getJIRAData/jql"
      Description: "JQL used to retrieve issues"
      Type: String
      Value: "project = XXX AND type = Story AND status = Done"
            
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetJIRADataFunction:
    Description: "getJIRAData Lambda Function ARN"
    Value: !GetAtt GetJIRADataFunction.Arn
  GetJIRADataRole:
    Description: "Explicit IAM Role created for Get JIRA Data function"
    Value: !GetAtt GetJIRADataRole.Arn